name: Trigger auto deployment for marketdata-api

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'Dockerfile.api'
    - 'S3CandlesDemo.Api/**'
    - 'S3CandlesDemo.Candles/**'
    - '.github/workflows/marketdata-api-AutoDeployTrigger-aa3f23b7-0870-436c-8224-6d665dc48c46.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.MARKETDATAAPI_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.MARKETDATAAPI_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.MARKETDATAAPI_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          dockerfilePath: Dockerfile.api
          _targetLabelKey_: _targetLabel_
          registryUrl: marketdataacr.azurecr.io
          registryUsername: ${{ secrets.MARKETDATAAPI_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.MARKETDATAAPI_REGISTRY_PASSWORD }}
          containerAppName: marketdata-api
          resourceGroup: marketdata-rg
          imageToBuild: marketdataacr.azurecr.io/marketdata-api:${{ github.sha }}
          targetPort: 8080
          _buildArgumentsKey_: |
            _buildArgumentsValues_


